name: Deploy CI
on:
  push:
    branches: ["master"]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    env:
      OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
      OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
      OAUTH_GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_SECRET }}
      OSS_ACCESS_KEY_SECRET: ${{ secrets.LEANCLOUD_APP_ID }}
      OAUTH_GITHUB_CLIENT_ID: ${{ secrets.LEANCLOUD_APP_KEY }}
      OAUTH_GITHUB_SECRET: ${{ secrets.LEANCLOUD_SERVER_URL }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run pre-deploy
      - run: npm run build --if-present
      - run: npm run deploy
